export const types = {
	RECIPE_CHECKED: 'RECIPE_CHECKED',
	RECIPE_UNCHECKED: 'RECIPE_UNCHECKED',
	FOUND_INGREDIENTS: 'FOUND_INGREDIENTS',
	FOUND_RECIPES: 'FOUND_RECIPES',
	SEARCH_RECIPE: 'SEARCH_RECIPE',
	SEND_DATA: 'SEND_DATA'
};